apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: tienda
type: Opaque
data:
  # admin123
  MYSQL_ROOT_PASSWORD: YWRtaW4xMjM=
  # alumno
  MYSQL_USER: YWx1bW5v
  # alumno123
  MYSQL_PASSWORD: YWx1bW5vMTIz
