name: CI Backend

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  validate-backend:
    name: Validar backend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Comprobar sintaxis
        run: node --check server.js
